# Generated by Django 3.2.9 on 2021-12-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20211211_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
